# for a complete reference, visit
# https://github.com/Macchina-CLI/macchina/wiki/Theme-Documentation
spacing = 2
padding = 0
hide_ascii = false
hide_bar_delimiters = true
prefer_small_ascii = false
separator = "->"
key_color = "LightCyan"
separator_color = "Magenta"
palette = "Full"

[bar]
glyph = "ß‹"
symbol_open = '['
symbol_close = ']'
visible = false

[box]
title = ""
visible = true

[box.inner_margin]
x = 2
y = 1

[custom_ascii]
color = "Blue"
path = "~/.config/macchina/ascii/artix.ascii"

[randomize]
key_color = false
separator_color = false

[keys]
host = "Host"
kernel = "Kernel"
battery = "Battery"
os = "OS"
de = "DE"
wm = "WM"
distro = "Distro"
terminal = "Terminal"
shell = "Shell"
packages = "Packages"
uptime = "Uptime"
memory = "Memory"
machine = "Machine"
local_ip = "IP"
backlight = "Brightness"
resolution = "Resolution"
cpu_load = "CPU Load"
cpu = "CPU"

