#!/usr/bin/env bash
#i3-msg workspace $(($(i3-msg -t get_workspaces | tr , '\n' | grep '"num":' | cut -d : -f 2 | sort -rn | head -1) + 1))
wine "$HOME/.wine/drive_c/Program Files (x86)/PyxelEdit/PyxelEdit.exe"
